<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Iugu
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list iugu-payment-icons">
    <li class="boleto on">
        <span><?php echo $this->__('Boleto') ?></span>
    </li>
</ul>
<?php if ($_instructions = $this->getInstructions()): ?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
            <?php echo nl2br($_instructions) ?>
        </div>
    </li>
</ul>
<?php endif; ?>
