<?php
/**
 * @category    Inovarti
 * @package     Inovarti_Iugu
 * @copyright   Copyright (c) 2014 Inovarti. (http://www.inovarti.com.br)
 */
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list iugu-payment-icons" id="<?php echo $_code ?>_types">
    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
        <li class="<?php echo $_typeCode ?> on">
            <span><?php echo $_typeName ?></span>
        </li>
    <?php endforeach ?>
</ul>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($_creditCards = $this->getCreditCards()): ?>
        <li id="iugu-credit-cards-box">
            <label for="<?php echo $_code ?>_customer_payment_method_id"><?php echo $this->__('Credit Card') ?></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_iugu_customer_payment_method_id" name="payment[iugu_customer_payment_method_id]" title="<?php echo $this->__('Credit Card') ?>">
                    <?php $_customerPaymentMethodId = $this->getInfoData('iugu_customer_payment_method_id') ?>
                    <?php foreach ($_creditCards as $_cc): ?>
                        <option value="<?php echo $_cc->getId() ?>"<?php if($_cc->getId()==$_customerPaymentMethodId): ?> selected="selected"<?php endif ?> data-cc-type="<?php echo Mage::getSingleton('iugu/source_cctype')->getTypeByBrand($_cc->getBrand()) ?>"><?php echo $_cc->getBrand() ?> <?php echo $_cc->getDisplayNumber() ?></option>
                    <?php endforeach ?>
                    <option value="" <?php if($_customerPaymentMethodId === ""): ?>selected="selected"<?php endif ?>><?php echo $this->__('New Credit Card') ?></option>
                </select>
            </div>
        </li>
        <script type="text/javascript">
            Event.observe($('<?php echo $_code ?>_iugu_customer_payment_method_id'), 'change', function() {
                var typesContainer = $(this.id.substr(0,this.id.indexOf('_iugu_customer_payment_method_id')) + '_types');
                if (this.value) {
                    $('payment_form_<?php echo $_code ?>').select('li').invoke('hide');
                    var ccType = null;
                    this.select('option').each(function(element) {
                       if (element.selected) {
                           ccType = element.readAttribute('data-cc-type');
                       }
                    });
                    typesContainer.select('li').invoke('removeClassName', 'on');
                    typesContainer.down('.' + ccType).addClassName('on');
                } else {
                    $('payment_form_<?php echo $_code ?>').select('li').invoke('show');
                    typesContainer.select('li').invoke('addClassName', 'on');
                }
                $('iugu-credit-cards-box').show();
                $('iugu-installments-box').show();
            });
            fireEvent($('<?php echo $_code ?>_iugu_customer_payment_method_id'), 'change');
        </script>
    <?php endif ?>
    <li style="display: none;">
        <input type="hidden" id="<?php echo $_code ?>_iugu_token" name="payment[iugu_token]" value="" />
        <select id="<?php echo $_code ?>_cc_type" title="<?php echo $this->__('Credit Card Type') ?>" style="display: none;">
            <option value=""><?php echo $this->__('--Please Select--') ?></option>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"><?php echo $_typeName ?></option>
            <?php endforeach ?>
        </select>
    </li>
    <li id="iugu-installments-box">
        <label for="<?php echo $_code ?>_installments" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_installments" name="payment[installments]" title="<?php echo $this->__('Installments') ?>" class="required-entry validate-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_installments = $this->getInfoData('installments') ?>
                <?php $_installmentsAvailables = $this->getInstallmentsAvailables() ?>
                <?php foreach ($_installmentsAvailables as $_installmentValue => $_installmentLabel): ?>
                    <option value="<?php echo $_installmentValue ?>"<?php if($_installmentValue==$_installments): ?> selected="selected"<?php endif ?>><?php echo $_installmentLabel ?></option>
                <?php endforeach ?>
            </select>
            <input type="hidden" id="<?php echo $_code ?>_installment_description" name="payment[installment_description]" value="<?php echo $this->escapeHtml($this->getInfoData('installment_description')) ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text iugu-only-number required-entry validate-iugu-cc-number" autocomplete="off" data-iugu="number" maxlength="19" value="" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" data-iugu="full_name" id="<?php echo $_code ?>_cc_owner" value="" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix iugu-cc-expr-month">
                <select id="<?php echo $_code ?>_expiration" class="month validate-iugu-cc-exp">
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix iugu-cc-expr-year">
                <span>/</span>
                <select id="<?php echo $_code ?>_expiration_yr" class="year">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <input type="hidden" id="<?php echo $_code ?>_cc_expiration" data-iugu="expiration" value="" />
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
        <li>
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix iugu-cvv">
                    <input type="text" id="<?php echo $_code ?>_cc_cid" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text iugu-only-number cvv required-entry validate-iugu-cc-cvn" autocomplete="off" data-iugu="verification_value" maxlength="4" value="" />
                    <div class="iugu-cvv-tool-tip">
                        <img src="<?php echo $this->getSkinUrl('iugu/images/icon_cvv.gif') ?>" class="iugu-cvv-icon" />
                        <div class="iugu-cvv-image"><img src="<?php echo $this->getSkinUrl('iugu/images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
                        <span class="iugu-cvv-tool-tip-arrow">&nbsp;</span>
                    </div>
                </div>
            </div>
        </li>
    <?php endif; ?>
    <li class="control">
        <input type="checkbox" name="payment[iugu_save]" id="<?php echo $_code ?>_save" value="1" <?php if($this->getInfoData('iugu_save')): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Save credit card') ?>" class="checkbox" /><label for="<?php echo $_code ?>_save"><?php echo $this->__('Save credit card') ?></label>
    </li>
</ul>
<script type="text/javascript">
    //<![CDATA[
    Event.observe($('<?php echo $_code ?>_installments'), 'change', function(){
        $(this.id.substr(0,this.id.indexOf('_installments')) + '_installment_description').value = this.selectedIndex > 0 ? this.options[this.selectedIndex].text : '';
    });

    Event.observe($('<?php echo $_code ?>_expiration'), 'change', function(){
        var month = ("0" + this.value).slice(-2);
        var year = $(this.id.substr(0,this.id.indexOf('_expiration')) + '_expiration_yr').value;
        $(this.id.substr(0,this.id.indexOf('_expiration')) + '_cc_expiration').value = month + '/' + year;
    });

    Event.observe($('<?php echo $_code ?>_expiration_yr'), 'change', function(){
        var month = ("0" + $(this.id.substr(0,this.id.indexOf('_expiration_yr')) + '_expiration').value).slice(-2);
        var year = this.value;
        $(this.id.substr(0,this.id.indexOf('_expiration')) + '_cc_expiration').value = month + '/' + year;
    });

    Event.observe($('<?php echo $_code ?>_cc_number'), 'change', function(){
        var skipChange = $(this.id.substr(0,this.id.indexOf('_cc_number')) + '_iugu_customer_payment_method_id')
            && $(this.id.substr(0,this.id.indexOf('_cc_number')) + '_iugu_customer_payment_method_id').value != "";
        if (skipChange) {
            return;
        }

        var typesContainer = $(this.id.substr(0,this.id.indexOf('_cc_number')) + '_types');
        var ccTypeContainer = $(this.id.substr(0,this.id.indexOf('_cc_number')) + '_cc_type');
        var ccCidContainer = $(this.id.substr(0,this.id.indexOf('_cc_number')) + '_cc_cid');
        var ccNumber = this.value;
        var ccType;

        if (ccNumber.length >= 6) {
            Validation.creditCartTypes.each(function (pair) {
                if (pair.value[3] && ccNumber.match(pair.value[3])) {
                    ccType = pair.key;
                    throw $break;
                }
            });
        }
        ccTypeContainer.value = ccType ? ccType : '';

        if (ccNumber) {
            typesContainer.select('li').invoke('removeClassName', 'on');
            if (ccType && ccType == ccTypeContainer.value) {
                typesContainer.down('.' + ccType).addClassName('on');
            }
        } else {
            typesContainer.select('li').invoke('addClassName', 'on');
        }

        if (ccCidContainer.value) {
            Validation.validate(ccCidContainer);
        }
    });

    Event.observe($('<?php echo $_code ?>_cc_number'), 'keyup', function(){
        fireEvent(this, 'change');
    });

    // allow only numbers
    $$('input.iugu-only-number').find(function(input){
        Event.observe(input, 'keydown', function(e){
            var code = e.keyCode || e.which;
            var isOnlyNumber = ((code > 47 && code < 58 && e.shiftKey == false)
            || (code > 95 && code < 106)
            || (e.ctrlKey || code == 8 || code == 9 || code == 13 || code == 16 || code == 35 || code == 36 || code == 37 || code == 38 || code == 39 || code == 40 || code == 46));

            if (!isOnlyNumber) {
                e.stop();
            }
        });

        Event.observe(input, 'blur', function(e){
            this.value = this.value.replace(/[^0-9]/g, '');
        });

        // prevent menu from right click
        Event.observe(input, 'contextmenu', function(e){
            e.stop();
        })
    });

    $$('input[name="payment[method]"]').find(function(radio) {
        Event.observe(radio, 'change', function() {
            if(radio.value == '<?php echo $_code ?>') {
                fireEvent($('<?php echo $_code ?>_cc_number'), 'change');
            } else {
                $('<?php echo $_code ?>_types').select('li').invoke('addClassName', 'on');
            }
        });
    });

    // Fill the form
    if (typeof payment !== "undefined" && payment.currentMethod == 'iugu_cc' && payment.iugu_cc_data) {
        $H(payment.iugu_cc_data).each(function(field){
            $(payment.currentMethod+'_'+field.key).value = field.value;
            fireEvent($(payment.currentMethod+'_'+field.key), 'change');
        });
    }

    fireEvent($('<?php echo $_code ?>_cc_number'), 'change');
    //]]>
</script>
