<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Iugu
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<img src="<?php echo $this->getSkinUrl('iugu/images/logo.png'); ?>" width="80" /><br />
<strong><?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?></strong>

<?php if($this->getInfo()): ?>
<br />
<?php echo $this->__('Invoice') ?>: <a href="#" onclick="return Iugu.load('<?php echo $this->getUrl('adminhtml/iugu_invoice/view', array('id' => $this->getInvoiceId())) ?>');"><?php echo $this->escapeHtml($this->getInvoiceId()) ?></a>
<br />
<a href="<?php echo $this->getInvoiceUrl() ?>" target="_blank"><?php echo $this->__('Click here to print your Boleto') ?></a>
<?php endif ?>
