<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Iugu
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>

<?php $_invoice = $this->getInvoice(); ?>
<div class="iugu-invoice-view-content">
    <div class="content-header">
        <table cellspacing="0">
            <tr>
                <td style="width:50%;"><h3 class="icon-head head-sales-order"><?php echo $this->__('Invoice: %s | %s', $_invoice->getId(), $_invoice->getCreatedAt()) ?></h3></td>
            </tr>
        </table>
    </div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo $this->__('Invoice Details') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo $this->__('Payment Method') ?></label></td>
                    <td class="value"><strong><?php echo $this->__('Boleto') ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Due Date') ?></label></td>
                    <td class="value"><strong><?php echo $this->escapeHtml($this->getDueDate()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Total') ?></label></td>
                    <td class="value"><strong class="emph"><?php echo $this->getTotal() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Status') ?></label></td>
                    <td class="value"><strong class="iugu-status <?php echo $_invoice->getStatus() ?>"><?php echo $this->escapeHtml($this->getStatusLabel()) ?></strong></td>
                </tr>
            </table>
        </div>
    </div>
</div>
