<?php
/**
 * @category   Inovarti
 * @package    Inovarti_Iugu
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php if($this->getTitle()): ?>
    <div class="page-title">
        <h1><?php echo $this->getTitle() ?></h1>
    </div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSavePaymentMethodUrl() ?>" method="post" id="form-payment" autocomplete="off">
    <?php $_code = 'iugu_cc'; ?>
    <ul class="form-list" id="payment_form_<?php echo $_code ?>">
        <li style="display: none;">
            <input type="hidden" id="<?php echo $_code ?>_token" name="payment[token]" value="" />
            <select id="<?php echo $_code ?>_cc_type" title="<?php echo $this->__('Credit Card Type') ?>" style="display: none;">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </li>
        <li>
            <ul class="form-list iugu-payment-icons" id="<?php echo $_code ?>_types">
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <li class="<?php echo $_typeCode ?> on">
                        <span><?php echo $_typeName ?></span>
                    </li>
                <?php endforeach ?>
            </ul>
        </li>
        <li>
            <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
            <div class="input-box">
                <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text iugu-only-number required-entry validate-iugu-cc-number" autocomplete="off" data-iugu="number" maxlength="19" value="" />
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" data-iugu="full_name" id="<?php echo $_code ?>_cc_owner" value="" />
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
            <div class="input-box">
                <div class="v-fix iugu-cc-expr-month">
                    <select id="<?php echo $_code ?>_expiration" class="month validate-iugu-cc-exp">
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix iugu-cc-expr-year">
                    <span>/</span>
                    <select id="<?php echo $_code ?>_expiration_yr" class="year">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <input type="hidden" id="<?php echo $_code ?>_cc_expiration" data-iugu="expiration" value="" />
            </div>
        </li>
        <?php echo $this->getChildHtml() ?>
        <li>
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix iugu-cvv">
                    <input type="text" id="<?php echo $_code ?>_cc_cid" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text iugu-only-number cvv required-entry validate-iugu-cc-cvn" autocomplete="off" data-iugu="verification_value" maxlength="4" value="" />
                    <div class="iugu-cvv-tool-tip">
                        <img src="<?php echo $this->getSkinUrl('iugu/images/icon_cvv.gif') ?>" class="iugu-cvv-icon" />
                        <div class="iugu-cvv-image"><img src="<?php echo $this->getSkinUrl('iugu/images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
                        <span class="iugu-cvv-tool-tip-arrow">&nbsp;</span>
                    </div>
                </div>
            </div>
        </li>
    </ul>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save Credit Card') ?>" class="button"><span><span><?php echo $this->__('Save Credit Card') ?></span></span></button>
    </div>
</form>
<script type="text/javascript" src="https://js.iugu.com/v2"></script>
<script type="text/javascript">
    //<![CDATA[
    Iugu.setAccountID('<?php echo $this->helper('iugu')->getAccountId(); ?>');
    <?php if($this->helper('iugu')->getMode() == Inovarti_Iugu_Model_Source_Mode::MODE_TEST): ?>
    Iugu.setTestMode(true);
    <?php endif ?>

    var dataForm = new VarienForm('form-payment', true);
    document.observe("dom:loaded", function() {
        Event.observe($('form-payment'), 'submit', function(event){
            if (dataForm.validator.validate()) {
                Iugu.createPaymentToken(this, function(data) {
                    if (data.errors) {
                        alert(JSON.stringify(data.errors));
                    } else {
                        $('<?php echo $_code ?>_token').value = data.id;
                        this.submit();
                    }
                }.bind(this));
            }
            Event.stop(event);
        });

        Event.observe($('<?php echo $_code ?>_expiration'), 'change', function () {
            var month = ("0" + this.value).slice(-2);
            var year = $(this.id.substr(0, this.id.indexOf('_expiration')) + '_expiration_yr').value;
            $(this.id.substr(0, this.id.indexOf('_expiration')) + '_cc_expiration').value = month + '/' + year;
        });

        Event.observe($('<?php echo $_code ?>_expiration_yr'), 'change', function () {
            var month = ("0" + $(this.id.substr(0, this.id.indexOf('_expiration_yr')) + '_expiration').value).slice(-2);
            var year = this.value;
            $(this.id.substr(0, this.id.indexOf('_expiration')) + '_cc_expiration').value = month + '/' + year;
        });

        Event.observe($('<?php echo $_code ?>_cc_number'), 'change', function () {
            var typesContainer = $(this.id.substr(0, this.id.indexOf('_cc_number')) + '_types');
            var ccTypeContainer = $(this.id.substr(0, this.id.indexOf('_cc_number')) + '_cc_type');
            var ccCidContainer = $(this.id.substr(0, this.id.indexOf('_cc_number')) + '_cc_cid');
            var ccNumber = this.value;
            var ccType;

            if (ccNumber.length >= 6) {
                Validation.creditCartTypes.each(function (pair) {
                    if (pair.value[3] && ccNumber.match(pair.value[3])) {
                        ccType = pair.key;
                        throw $break;
                    }
                });
            }
            ccTypeContainer.value = ccType ? ccType : '';

            if (ccNumber) {
                typesContainer.select('li').invoke('removeClassName', 'on');
                if (ccType && ccType == ccTypeContainer.value) {
                    typesContainer.down('.' + ccType).addClassName('on');
                }
            } else {
                typesContainer.select('li').invoke('addClassName', 'on');
            }

            if (ccCidContainer.value) {
                Validation.validate(ccCidContainer);
            }
        });

        Event.observe($('<?php echo $_code ?>_cc_number'), 'keyup', function () {
            fireEvent(this, 'change');
        });

        // allow only numbers
        $$('input.iugu-only-number').find(function (input) {
            Event.observe(input, 'keydown', function (e) {
                var code = e.keyCode || e.which;
                var isOnlyNumber = ((code > 47 && code < 58 && e.shiftKey == false)
                || (code > 95 && code < 106)
                || (e.ctrlKey || code == 8 || code == 9 || code == 13 || code == 16 || code == 35 || code == 36 || code == 37 || code == 38 || code == 39 || code == 40 || code == 46));

                if (!isOnlyNumber) {
                    e.stop();
                }
            });

            Event.observe(input, 'blur', function (e) {
                this.value = this.value.replace(/[^0-9]/g, '');
            });

            // prevent menu from right click
            Event.observe(input, 'contextmenu', function (e) {
                e.stop();
            });
        });

        fireEvent($('<?php echo $_code ?>_cc_number'), 'change');
    });
    //]]>
</script>
