<?php
/**
 * @category   Inovarti
 * @package    Inovarti_Iugu
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php $_items = $this->getItems(); ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('My Credit Cards') ?></h1>
    <button type="button" title="<?php echo $this->__('Add New Credit Card') ?>" class="button" onclick="window.location='<?php echo $this->getAddPaymentMethodUrl() ?>';"><span><span><?php echo $this->__('Add New Credit Card') ?></span></span></button>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if(count($_items)): ?>
    <table class="data-table" id="my-payment-methods-table">
        <col width="1" />
        <col />
        <col />
        <col width="1" />
        <thead>
            <tr>
                <th><?php echo Mage::helper('iugu')->__('Type') ?></th>
                <th><?php echo Mage::helper('iugu')->__('Credit Card Number') ?></th>
                <th><?php echo Mage::helper('iugu')->__('Added At') ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($_items as $_item): ?>
            <?php $_paymentInfo = $_item->getData('data'); ?>
            <tr>
                <td><ul class="iugu-payment-icons"><li class="<?php echo Mage::getModel('iugu/source_cctype')->getTypeByBrand($_paymentInfo->getBrand()) ?> on">&nbsp;</li></td>
                <td><span class="nobr"><?php echo $_paymentInfo->getDisplayNumber() ?></span></td>
                <td><?php echo Mage::getModel('core/date')->date('d/m/Y', $_item->getDescription()) ?></td>
                <td class="a-center">
                    <span class="nobr">
                        <a class="btn-remove btn-remove2" title="<?php echo $this->__('Remove this credit card') ?>" href="#" onclick="return deletePaymentMethod('<?php echo $this->getUrl('*/*/delete', array('id' => $_item->getId())) ?>');"><?php echo $this->__('Delete') ?></a>
                    </span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-payment-methods-table')</script>
<?php else: ?>
    <p><?php echo Mage::helper('iugu')->__('You have not added any credit card yet.'); ?></p>
<?php endif ?>

<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
<script type="text/javascript">
    function deletePaymentMethod(url) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this credit card?') ?>')) {
            window.location=url;
        }
        return false;
    }
</script>
